version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"                   : "jdbc:mysql://mysqldb:3306/demo_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
              "spring.datasource.username"              : "root",
              "spring.datasource.password"              : "root",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto"           : "update"
            }'
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  db: